# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_type',
            field=models.CharField(choices=[('POEM', 'poem'), ('ARTICLE', 'article')], default='POEM', max_length=7, verbose_name='Article Type'),
        ),
    ]
